"""add match_id to notifications

Revision ID: 5cd21abe0f6d
Revises: 88ed2818cdcc
Create Date: 2026-07-09 23:14:23.138046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd21abe0f6d'
down_revision: Union[str, Sequence[str], None] = '88ed2818cdcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('match_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_match_id'), 'notifications', ['match_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'matches', ['match_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_match_id'), table_name='notifications')
    op.drop_column('notifications', 'match_id')
    # ### end Alembic commands ###
