"""add qualified_team_id to matches

Revision ID: 88ed2818cdcc
Revises: 8f38f87dda9a
Create Date: 2026-07-07 21:20:54.110904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ed2818cdcc'
down_revision: Union[str, Sequence[str], None] = '8f38f87dda9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('qualified_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'teams', ['qualified_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'qualified_team_id')
    # ### end Alembic commands ###
